# Generated by Django 3.1.3 on 2020-12-04 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('url', models.CharField(blank=True, max_length=255, null=True)),
                ('time', models.CharField(blank=True, max_length=255, null=True)),
                ('genre', models.CharField(blank=True, max_length=255, null=True)),
                ('release_time', models.DateField(blank=True, null=True)),
                ('intro', models.CharField(blank=True, max_length=255, null=True)),
                ('directors', models.CharField(blank=True, max_length=255, null=True)),
                ('writers', models.CharField(blank=True, max_length=255, null=True)),
                ('starts', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'movies',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Ratings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField(blank=True, db_column='userId', null=True)),
                ('movieid', models.IntegerField(blank=True, db_column='movieId', null=True)),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('timestamp', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'ratings',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField(blank=True, db_column='userId', null=True)),
                ('movieid', models.IntegerField(blank=True, db_column='movieId', null=True)),
                ('tag', models.CharField(blank=True, max_length=255, null=True)),
                ('timestamp', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'tags',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
    ]
