# Generated by Django 3.1.3 on 2020-12-07 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0002_collect_search'),
    ]

    operations = [
        migrations.CreateModel(
            name='rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField(blank=True, db_column='userId', null=True)),
                ('movieid', models.IntegerField(blank=True, db_column='movieId', null=True)),
                ('rating', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
